### ISSUE TITLE
Further fixes for responsiveness needed

### ISSUE THREAD

**Issue by Virus5600** [Virus5600/Party-Color-Reservation-System#23]
Various pages still breaks when viewed on different sizes.

Please add all pages as a task list so that we can keep track of all pages done already.

**Comment by Virus5600** [comment]
Follow up fix. The elements are phasing above the navigation bar.
![Image](https://user-images.githubusercontent.com/19548426/219885132-cbeefb23-385d-4393-bfca-be1e059d06a0.png)

**Comment by JM-Elbambo** [comment]
- [x] Reservation page

**Comment by Virus5600** [comment]
Fix for this:
![Image](https://user-images.githubusercontent.com/19548426/220592381-63d0a389-ee95-4fee-9891-9823105a344c.png)

**Comment by Virus5600** [comment]
Assuming responsiveness is already fixed. Closing issue.
