### ISSUE TITLE
Addition of single fetch announcement endpoint

### ISSUE THREAD

**Issue by Virus5600** [Virus5600/Party-Color-Reservation-System#33]
Individual fetching of announcements to allow viewing and parameter passing. This is in conjunction with Issue #28

**Comment by Virus5600** [comment]
Need more information regarding this endpoint @KrimssmirK . Please provide the list of parameters that will be sent so I can thoroughly create the endpoint properly. Thank you.

**Comment by KrimssmirK** [comment]
gusto kong ma fetch individual ung announcement based on sa id nya

**Comment by Virus5600** [comment]
Commit 9ba2180 implements the requested API endpoint
